
FROM node:18-alpine

WORKDIR /app


COPY package.json package-lock.json* ./
RUN npm install


COPY . .

RUN addgroup -g 1001 -S nodejs && \
    adduser -S nextjs -u 1001


RUN chown -R nextjs:nodejs /app
USER nextjs

EXPOSE 3000

ENV NODE_ENV=development

# Command to run in development mode
CMD ["npm", "run", "dev"]